export type GiftTheme = {
  id: string;
  name: string;
  description: string;
  background: string;
  borderColor: string;
  textColor: string;
  accentColor: string;
  icon: string;
  preview?: string;
};

export const occasionThemes: Record<string, GiftTheme[]> = {
  birthday: [
    {
      id: 'birthday-party',
      name: 'Birthday Party',
      description: 'Colorful and festive celebration',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1514525253161-7a46d19cd819')`,
      borderColor: 'border-purple-300',
      textColor: 'text-white',
      accentColor: 'bg-yellow-400',
      icon: '🎂',
    },
    {
      id: 'birthday-sparkle',
      name: 'Birthday Sparkle',
      description: 'Elegant and sparkly design',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1513151233558-d860c5398176')`,
      borderColor: 'border-blue-300',
      textColor: 'text-white',
      accentColor: 'bg-blue-300',
      icon: '✨',
    },
    {
      id: 'birthday-balloon',
      name: 'Balloon Fiesta',
      description: 'Vibrant balloon celebration',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1530103862676-de8c9debad1d')`,
      borderColor: 'border-pink-300',
      textColor: 'text-white',
      accentColor: 'bg-pink-400',
      icon: '🎈',
    },
    {
      id: 'birthday-confetti',
      name: 'Confetti Blast',
      description: 'Explosive celebration vibes',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1514525253161-7a46d19cd819')`,
      borderColor: 'border-indigo-300',
      textColor: 'text-white',
      accentColor: 'bg-indigo-400',
      icon: '🎉',
    },
    {
      id: 'birthday-cake',
      name: 'Sweet Celebration',
      description: 'Delightful cake theme',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec')`,
      borderColor: 'border-rose-300',
      textColor: 'text-white',
      accentColor: 'bg-rose-400',
      icon: '🧁',
    },
    {
      id: 'birthday-lights',
      name: 'Party Lights',
      description: 'Magical light show',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1492684223066-81342ee5ff30')`,
      borderColor: 'border-amber-300',
      textColor: 'text-white',
      accentColor: 'bg-amber-400',
      icon: '💫',
    },
  ],
  valentine: [
    {
      id: 'valentine-romance',
      name: 'Classic Romance',
      description: 'Timeless love theme',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1518199266791-5375a83190b7')`,
      borderColor: 'border-red-300',
      textColor: 'text-white',
      accentColor: 'bg-red-400',
      icon: '❤️',
    },
    {
      id: 'valentine-roses',
      name: 'Rose Garden',
      description: 'Romantic rose theme',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00')`,
      borderColor: 'border-pink-300',
      textColor: 'text-white',
      accentColor: 'bg-pink-400',
      icon: '🌹',
    },
    {
      id: 'valentine-heart',
      name: 'Heart & Soul',
      description: 'Pure love expression',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1516589091380-5d8e87df6999')`,
      borderColor: 'border-rose-300',
      textColor: 'text-white',
      accentColor: 'bg-rose-400',
      icon: '💝',
    },
    {
      id: 'valentine-sunset',
      name: 'Love Sunset',
      description: 'Romantic evening vibes',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1516483638261-f4dbaf036963')`,
      borderColor: 'border-orange-300',
      textColor: 'text-white',
      accentColor: 'bg-orange-400',
      icon: '🌅',
    },
    {
      id: 'valentine-chocolate',
      name: 'Sweet Love',
      description: 'Chocolate romance',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1549007994-cb92caebd54b')`,
      borderColor: 'border-amber-300',
      textColor: 'text-white',
      accentColor: 'bg-amber-400',
      icon: '🍫',
    },
    {
      id: 'valentine-flowers',
      name: 'Floral Love',
      description: 'Blooming romance',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00')`,
      borderColor: 'border-purple-300',
      textColor: 'text-white',
      accentColor: 'bg-purple-400',
      icon: '💐',
    },
  ],
  christmas: [
    {
      id: 'christmas-classic',
      name: 'Classic Christmas',
      description: 'Traditional holiday spirit',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1543589077-47d81606c1bf')`,
      borderColor: 'border-red-300',
      textColor: 'text-white',
      accentColor: 'bg-red-400',
      icon: '🎄',
    },
    {
      id: 'christmas-snow',
      name: 'Winter Wonder',
      description: 'Snowy Christmas scene',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1482517967863-00e15c9b44be')`, // New winter scene
      borderColor: 'border-blue-300',
      textColor: 'text-white',
      accentColor: 'bg-blue-400',
      icon: '❄️',
    },
    {
      id: 'christmas-gifts',
      name: 'Gift Time',
      description: 'Festive presents',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1512389142860-9c449e58a543')`,
      borderColor: 'border-green-300',
      textColor: 'text-white',
      accentColor: 'bg-green-400',
      icon: '🎁',
    },
    {
      id: 'christmas-cozy',
      name: 'Cozy Christmas',
      description: 'Warm holiday feeling',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1479722842840-c0a823bd0cd6')`,
      borderColor: 'border-amber-300',
      textColor: 'text-white',
      accentColor: 'bg-amber-400',
      icon: '🕯️',
    },
    {
      id: 'christmas-lights',
      name: 'Holiday Lights',
      description: 'Magical illumination',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1576692155415-95f820a2c4c1')`,
      borderColor: 'border-yellow-300',
      textColor: 'text-white',
      accentColor: 'bg-yellow-400',
      icon: '✨',
    },
    {
      id: 'christmas-night',
      name: 'Silent Night',
      description: 'Peaceful evening scene',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1543258103-a62bdc069871')`, // New winter night scene
      borderColor: 'border-indigo-300',
      textColor: 'text-white',
      accentColor: 'bg-indigo-400',
      icon: '🌙',
    },
  ],
  graduation: [
    {
      id: 'graduation-classic',
      name: 'Classic Grad',
      description: 'Traditional achievement',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1523050854058-8df90110c9f1')`,
      borderColor: 'border-blue-300',
      textColor: 'text-white',
      accentColor: 'bg-blue-400',
      icon: '🎓',
    },
    {
      id: 'graduation-future',
      name: 'Bright Future',
      description: 'New beginnings',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1532649538693-f3a2ec1bf8bd')`,
      borderColor: 'border-purple-300',
      textColor: 'text-white',
      accentColor: 'bg-purple-400',
      icon: '🚀',
    },
    {
      id: 'graduation-success',
      name: 'Success Path',
      description: 'Achievement celebration',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5')`,
      borderColor: 'border-emerald-300',
      textColor: 'text-white',
      accentColor: 'bg-emerald-400',
      icon: '⭐',
    },
    {
      id: 'graduation-library',
      name: 'Scholar',
      description: 'Academic excellence',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1524995997946-a1c2e315a42f')`,
      borderColor: 'border-amber-300',
      textColor: 'text-white',
      accentColor: 'bg-amber-400',
      icon: '📚',
    },
    {
      id: 'graduation-celebration',
      name: 'Celebration',
      description: 'Joyful achievement',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1541339907198-e08756dedf3f')`,
      borderColor: 'border-rose-300',
      textColor: 'text-white',
      accentColor: 'bg-rose-400',
      icon: '🎉',
    },
    {
      id: 'graduation-wisdom',
      name: 'Wisdom',
      description: 'Knowledge & growth',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1546410531-bb4caa6b424d')`,
      borderColor: 'border-cyan-300',
      textColor: 'text-white',
      accentColor: 'bg-cyan-400',
      icon: '🌟',
    },
  ],
  wedding: [
    {
      id: 'wedding-elegant',
      name: 'Elegant',
      description: 'Timeless romance',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1519225421980-715cb0215aed')`,
      borderColor: 'border-rose-300',
      textColor: 'text-white',
      accentColor: 'bg-rose-400',
      icon: '💒',
    },
    {
      id: 'wedding-floral',
      name: 'Floral Dream',
      description: 'Blooming love',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1519741347686-c1e0aadf4611')`,
      borderColor: 'border-pink-300',
      textColor: 'text-white',
      accentColor: 'bg-pink-400',
      icon: '💐',
    },
    {
      id: 'wedding-golden',
      name: 'Golden Romance',
      description: 'Luxurious celebration',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1511795409834-ef04bbd61622')`,
      borderColor: 'border-amber-300',
      textColor: 'text-white',
      accentColor: 'bg-amber-400',
      icon: '💍',
    },
    {
      id: 'wedding-rustic',
      name: 'Rustic Love',
      description: 'Natural beauty',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1510076857177-7470076d4098')`,
      borderColor: 'border-stone-300',
      textColor: 'text-white',
      accentColor: 'bg-stone-400',
      icon: '🌿',
    },
    {
      id: 'wedding-classic',
      name: 'Classic White',
      description: 'Traditional elegance',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1517722014278-c256a91a6fba')`,
      borderColor: 'border-slate-300',
      textColor: 'text-white',
      accentColor: 'bg-slate-400',
      icon: '👰',
    },
    {
      id: 'wedding-romantic',
      name: 'Romance',
      description: 'Pure love celebration',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8')`,
      borderColor: 'border-red-300',
      textColor: 'text-white',
      accentColor: 'bg-red-400',
      icon: '❤️',
    },
  ],
  other: [
    {
      id: 'other-celebration',
      name: 'Celebration',
      description: 'Special moments',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1513151233558-d860c5398176')`,
      borderColor: 'border-purple-300',
      textColor: 'text-white',
      accentColor: 'bg-purple-400',
      icon: '🎉',
    },
    {
      id: 'other-nature',
      name: 'Nature',
      description: 'Natural beauty',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1501854140801-50d01698950b')`,
      borderColor: 'border-green-300',
      textColor: 'text-white',
      accentColor: 'bg-green-400',
      icon: '🌿',
    },
    {
      id: 'other-minimal',
      name: 'Minimal',
      description: 'Clean & simple',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1507878866276-a947ef722fee')`,
      borderColor: 'border-gray-300',
      textColor: 'text-white',
      accentColor: 'bg-gray-400',
      icon: '✨',
    },
    {
      id: 'other-modern',
      name: 'Modern',
      description: 'Contemporary style',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), ('https://images.unsplash.com/photo-1507842217343-583bb7270b66')`,
      borderColor: 'border-zinc-300',
      textColor: 'text-white',
      accentColor: 'bg-zinc-400',
      icon: '🎯',
    },
    {
      id: 'other-abstract',
      name: 'Abstract',
      description: 'Artistic design',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1541701494587-cb58502866ab')`,
      borderColor: 'border-indigo-300',
      textColor: 'text-white',
      accentColor: 'bg-indigo-400',
      icon: '🎨',
    },
    {
      id: 'other-classic',
      name: 'Classic',
      description: 'Timeless style',
      background: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://images.unsplash.com/photo-1492551557933-34265f7af79e')`,
      borderColor: 'border-slate-300',
      textColor: 'text-white',
      accentColor: 'bg-slate-400',
      icon: '🎭',
    },
  ],
};

export const defaultTheme: GiftTheme = occasionThemes.other[0];

export function getThemesByOccasion(occasion: string): GiftTheme[] {
  return occasionThemes[occasion] || occasionThemes.other;
}
